### ISSUE TITLE
ERROR Rack::Lint::LintError: The file identified by body.to_path does not exist

### ISSUE THREAD

**Issue by lifeinafolder** [livingsocial/rake-pipeline#131]
I often see this error in the logs of `rakep server`

```
ERROR Rack::Lint::LintError: The file identified by body.to_path does not exist
    /Users/rajat/.rvm/gems/ruby-1.9.2-p320/gems/rack-1.4.1/lib/rack/lint.rb:19:in `assert'
    /Users/rajat/.rvm/gems/ruby-1.9.2-p320/gems/rack-1.4.1/lib/rack/lint.rb:543:in `each'
    /Users/rajat/.rvm/gems/ruby-1.9.2-p320/gems/rack-1.4.1/lib/rack/body_proxy.rb:26:in `method_missing'
    /Users/rajat/.rvm/gems/ruby-1.9.2-p320/gems/rack-1.4.1/lib/rack/chunked.rb:23:in `each'
    /Users/rajat/.rvm/gems/ruby-1.9.2-p320/gems/rack-1.4.1/lib/rack/handler/webrick.rb:71:in `service'
    /Users/rajat/.rvm/rubies/ruby-1.9.2-p320/lib/ruby/1.9.1/webrick/httpserver.rb:111:in `service'
    /Users/rajat/.rvm/rubies/ruby-1.9.2-p320/lib/ruby/1.9.1/webrick/httpserver.rb:70:in `run'
    /Users/rajat/.rvm/rubies/ruby-1.9.2-p320/lib/ruby/1.9.1/webrick/server.rb:183:in `block in start_thread'
```

This mostly costs me an extra refresh or restarting the server as some of the assets on the requested page are not loaded.

Any pointers why?

**Comment by ianpetzer** [comment]
I'm also experiencing. Any suggestions on how to find the offending code?
